import type { Metadata } from "next";
import { ThemeProvider } from 'next-themes';
import SkipToMainContent from '@/components/SkipToMainContent';
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="antialiased">
        {/* CRITICAL: Skip link MUST be first focusable element */}
        <SkipToMainContent />
        {/* No-JS warning banner (Story 7.6: Progressive Enhancement) */}
        <noscript>
          <div className="no-js-banner">
            <p>
              <strong>JavaScript is disabled.</strong> For the best experience, please enable JavaScript in your browser settings.
            </p>
          </div>
        </noscript>
        <ThemeProvider attribute="data-theme" defaultTheme="dark" enableSystem>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
